project:
  type: book
  output-dir: docs
book:
  title: NZILBB R and Open Science Workshops
  author:
  - name: Joshua Wilson Black
    orcid: 0000-0002-8272-5763
  date: today
  repo-url: https://github.com/nzilbb/statistics_workshops
  repo-actions: [edit, issue]
  chapters:
  - index.qmd
  - part: chapters/foundations.qmd
    chapters: 
    - chapters/getting_started.qmd
    - chapters/data_processing.qmd
    - chapters/exploratory_data_vis.qmd
    - chapters/linear_models.qmd
  - part: chapters/others.qmd
    chapters: 
    - chapters/rstudio_server.qmd
    - chapters/qualtrics.qmd
    - chapters/gamms_1.qmd
  - chapters/references.qmd
  sidebar:
    logo: global_images/nzilbb-logo.svg
bibliography: 
  - stat_workshops.bib
  - grateful-refs.bib
format:
  html:
    theme:
    - flatly
    - theme.scss
    css: include/webex.css
    include-in-header:
      - text: |
          <link rel="icon" type="image/png" sizes="32x32" href=".//global_images/fav.png" />
    include-after-body: include/webex.js
    code-summary: "To view the code click here"
    df-print: tibble
    execute:
      warning: false
