project:
  type: book
book:
  title: NZILBB R and Open Science Workshops
  author:
  - name: Joshua Wilson Black
    orcid: 0000-0002-8272-5763
  date: today
  chapters:
  - index.qmd
  - intro.qmd
  - part: foundations.qmd
    chapters: 
    - getting_started.qmd
  - part: others.qmd
    chapters: 
    - rstudio_server.qmd
    - qualtrics.qmd
  - references.qmd
  sidebar:
    logo: images/nzilbb-logo.svg
bibliography: references.bib
format:
  html:
    theme:
    - flatly
    - theme.scss
    css: include/webex.css
    include-after-body: include/webex.js
  pdf:
    documentclass: scrreprt
